name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.dir }}
    strategy:
      fail-fast: false
      matrix:
        dir: [playwright-test, vitest-test]
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 10.28.1

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: pnpm install --frozen-lockfile

      - run: pnpm exec playwright install webkit

      - run: pnpm test
