name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        browser: [chromium, firefox, webkit]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: pnpm install --frozen-lockfile

      - run: pnpm exec playwright install --with-deps

      - run: pnpm test
        env:
          TEST_BROWSER: ${{ matrix.browser }}
